config/routes.rb
Rails.application.routes.draw do

  root 'home#index'
  get 'abc/abc' => "home#index"

  get 'refresh' => 'home#refresh'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    match_pattern = /^[1-9]([0-9]*)?$/
    @from = params[:from]
    @to = params[:to]
    @secret = params[:secret] || "68afc34d981f1a94056757e32f20b9c6"
    audience = params[:audience]

    if @from && @to
      if @from =~ match_pattern && @to =~ match_pattern
        if @from.to_i > @to.to_i
          @action = "NOTHING"
        else
          @action = "MULTIPLE"
          cookies[:__audience] = @from
        end
      else
        @action = "NOTHING"
      end
    else
      @action = "SINGLE"
      cookies[:__audience] = audience
    end
  end

  def refresh
    cookies.clear
    @from = params[:from]
    @to = params[:to]
    redirect_to root_path(from: @from, to: @to)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.erb
<% if @action == "MULTIPLE" %>
  <%= link_to "refresh", refresh_path(from: @from.to_i + 1, to: @to.to_i),
    id: "refresh" %>
<% end %>
<%= link_to "sample", root_path %>

<script>
  $(function(){
    // var date = new Date();
    // date.setTime(date.getTime()-(24*60*60*1000));
    // date.toGMTString()
    // PinPoint.Cookies.set({key: "_pp_xd", value: "", domain: ".wala.herokuapp.com", path: "/", expires: d });

    <% if @action.in? ["SINGLE", "MULTIPLE"] %>
      console.log("Run GOOGLE run!")
      PinPoint.init(@secret, PinPoint.Cookies.get("__audience")).track();
      // (new PinPoint.Track("357230d84988ff164005e87a74cc6bea", PinPoint.Cookies.get("__audience"))).track();
    <% end %>
    <% if @action == "MULTIPLE" %>
      console.log("Go MULTIPLE!")
      setTimeout(function(){
        $("#refresh")[0].click();
      }, 1000);
    <% end %>
    <% if @action == "NOTHING" %>
      console.log("NOTHING to do here!")
    <% end %>
  });
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Wala</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag "http://dev0.pin-pg.com/pinpoint.js" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>